---
- name: Ensures Xvfb package is installed
  become: true
  community.general.apk:
    name: xvfb
    state: present
    update_cache: true
- name: Ensures libx11 package is installed
  become: true
  community.general.apk:
    name: libx11
    state: present
  when: xvfb_install_x11_utils
