---
- name: Ensures Xvfb package is installed
  become: true
  community.general.apk:
    name: xvfb
    state: present
    update_cache: true

- name: Ensures libx11 package is installed
  become: true
  community.general.apk:
    name: libx11
    state: present
  when: xvfb_install_x11_utils

- name: Ensure Xvfb is service installed
  become: "{{ ansible_user_id != 'root' }}"
  when: xvfb_service_enabled
  block:

    - name: Ensure supervisor is installed
      become: true
      community.general.apk:
        name: supervisor
        state: present
        update_cache: true

    - name: Include configuration tasks for supervisor
      ansible.builtin.include_tasks:
        file: supervisord.yml
