---
- name: Ensures Xvfb package is installed
  ansible.builtin.apt:
    install_recommends: false
    name: xvfb
    state: present
    update_cache: true
  become: "{{ ansible_user_id != 'root' }}"
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Ensures X11 utils are installed
  ansible.builtin.apt:
    name: x11-utils
    state: present
  become: "{{ ansible_user_id != 'root' }}"
  when: xvfb_install_x11_utils
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Ensure Xvfb is service installed
  become: "{{ ansible_user_id != 'root' }}"
  when: xvfb_service_enabled
  block:

    - name: Ensure supervisor is installed
      ansible.builtin.apt:
        name: supervisor
        state: present
        update_cache: true
      environment:
        DEBIAN_FRONTEND: noninteractive

    - name: Include configuration tasks for supervisor
      ansible.builtin.include_tasks:
        file: supervisord.yml

- name: Clean apt cache and perform package housekeeping
  ansible.builtin.apt:
    autoclean: true
    autoremove: true
    purge: true
    update_cache: true
  become: "{{ ansible_user_id != 'root' }}"
  changed_when: false
  environment:
    DEBIAN_FRONTEND: noninteractive
