---
- name: Ensures Xvfb package is installed
  ansible.builtin.apt:
    install_recommends: !!str no
    name: xvfb
    state: present
    update_cache: !!str yes
  become: "{{ ansible_user_id != 'root' }}"

- name: Ensure Xvfb is service installed
  become: "{{ ansible_user_id != 'root' }}"
  when: xvfb_service_enabled
  block:

    - name: Ensure supervisor is installed
      ansible.builtin.apt:
        name: supervisor
        state: present
        update_cache: true

    - name: Include configuration tasks for supervisor
      ansible.builtin.include_tasks:
        file: supervisord.yml

- name: Clean apt cache and perform package housekeeping
  ansible.builtin.apt:
    autoclean: !!str yes
    autoremove: !!str yes
    purge: !!str yes
    update_cache: !!str yes
  become: "{{ ansible_user_id != 'root' }}"
