---
- name: Install Xvfb package
  ansible.builtin.apt:
    install_recommends: !!str no
    name: xvfb
    state: present
    update_cache: !!str yes
  become: true
- name: Create Xvfb profile
  ansible.builtin.template:
    dest: /etc/profile.d/10-xvfb.sh
    mode: 0644
    src: profile-d-xvfb.j2
- name: Create Xvfb service
  ansible.builtin.template:
    src: init-d-xvfb-Debian.j2
    dest: /etc/init.d/xvfb
    mode: 0755
  become: true
- name: Start Xvfb service
  ansible.builtin.service:
    name: xvfb
    enabled: !!str yes
    state: started
  become: true
