---
- name: Ensures Xvfb package is installed
  ansible.builtin.apt:
    install_recommends: !!str no
    name: xvfb
    state: present
    update_cache: !!str yes
  become: true
- name: Ensures Xvfb profile is created
  ansible.builtin.template:
    dest: /etc/profile.d/10-xvfb.sh
    mode: "0644"
    src: profile-d-xvfb.j2
  become: true
- name: Ensures Xvfb service is created
  ansible.builtin.template:
    src: init-d-xvfb-Debian.j2
    dest: /etc/init.d/xvfb
    mode: "0755"
  become: true
  when: xvfb_service_enabled
- name: Ensures Xvfb service is started
  ansible.builtin.service:
    name: xvfb
    enabled: true
    state: started
  become: true
  when: xvfb_service_enabled
- name: Ensures x11-utils package is installed
  ansible.builtin.apt:
    install_recommends: !!str no
    name: x11-utils
    state: present
  become: true
  when: xvfb_install_x11_utils
