---
- name: Includes operating system specific tasks to install Xvfb
  ansible.builtin.include_tasks:
    file: "{{ ansible_os_family }}.yml"
  tags: xvfb
  when: xvfb_role_fact.get('xvfb_package_installed', false) | bool

- name: Get supervisord status for Xvfb
  community.general.supervisorctl:
    name: xvfb
    state: present
  when: xvfb_service_enabled | bool
