---
- name: Check if Nix store exists
  ansible.builtin.stat:
    path: /nix/store
  register: nix_store_stat

- name: Ensure required packages are installed
  become: "{{ ansible_user_id != 'root' }}"
  when: nix_store_stat.stat.exists
  block:

    - name: Get list of installed Nix packages
      ansible.builtin.command: nix-env -q
      register: installed_packages
      failed_when: false
      changed_when: false

    - name: Ensure packages are installed
      ansible.builtin.command: nix-env -iA {{ item.package }}
      loop: "{{ xvfb_nixos_install_pkgs }}"
      loop_control:
        label: "{{ item.name }}"
      when: installed_packages.stdout_lines | default([]) | select('search', item.name) | list | length == 0
      changed_when: true

- name: Include configuration tasks for supervisor
  ansible.builtin.include_tasks:
    file: supervisord.yml
