---
- name: Check if Nix store exists
  ansible.builtin.stat:
    path: /nix/store
  register: nix_store_stat

- name: Ensure Xvfb is installed
  become: "{{ ansible_user_id != 'root' }}"
  block:

    - name: Check if Xvfb is already installed
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          nix-env -q | grep -q xorg-server
      changed_when: false
      failed_when: xvfb_check.rc not in [0, 1]
      register: xvfb_check
      when: nix_store_stat.stat.exists

    - name: Ensure Xvfb package is installed on Nix image
      ansible.builtin.command: nix-env -iA nixpkgs.xorg.xvfb
      when:
        - nix_store_stat.stat.exists
        - xvfb_check.rc != 0
      register: xvfb_install
      changed_when: xvfb_install.rc == 0

- name: Ensure Xvfb is service installed
  become: "{{ ansible_user_id != 'root' }}"
  when: xvfb_service_enabled
  block:

    - name: Check if supervisor is already installed
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          nix-env -q | grep -q supervisor
      changed_when: false
      failed_when: supervisor_check.rc not in [0, 1]
      register: supervisor_check
      when: nix_store_stat.stat.exists

    - name: Ensure supervisor is installed
      ansible.builtin.command: nix-env -iA nixpkgs.python3Packages.supervisor
      when:
        - nix_store_stat.stat.exists
        - supervisor_check.rc != 0
      register: supervisor_install
      changed_when: supervisor_install.rc == 0

    - name: Ensure necessary directories exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - /etc/profile.d
        - /etc/supervisor/conf.d
        - /var/log/supervisor
        - /var/run

    - name: Ensures Xvfb profile is created
      ansible.builtin.template:
        dest: /etc/profile.d/10-xvfb.sh
        mode: "0644"
        src: profile-d-xvfb.j2

    - name: Create supervisor configuration file
      ansible.builtin.template:
        src: supervisord-xvfb.conf.j2
        dest: /etc/supervisor/supervisord.conf
        mode: "0644"

    - name: Create Xvfb supervisor program configuration
      ansible.builtin.template:
        src: supervisord-xvfb-program.conf.j2
        dest: /etc/supervisor/conf.d/xvfb.conf
        mode: "0644"

    - name: Start supervisor daemon
      ansible.builtin.shell: |
        supervisord -c /etc/supervisor/supervisord.conf
      args:
        creates: /var/run/supervisor.pid
