---
- name: Check if Nix store exists
  ansible.builtin.stat:
    path: /nix/store
  register: nix_store_stat

- name: Ensure required packages are installed
  become: "{{ ansible_user_id != 'root' }}"
  when: nix_store_stat.stat.exists
  block:

    - name: Check if packages are already installed
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          nix-env -q | grep -q ^{{ item.name }}
      changed_when: false
      failed_when: pkg_check.rc not in [0, 1]
      loop: "{{ xvfb_nixos_install_pkgs }}"
      register: pkg_check
      when: nix_store_stat.stat.exists

    - name: Ensure packages are installed
      ansible.builtin.command: nix-env -iA {{ item.0.package }}
      changed_when: pkg_install.rc == 0
      loop: "{{ xvfb_nixos_install_pkgs | zip(pkg_check.results) | list }}"
      loop_control:
        label: "{{ item.0.name }}"
      register: pkg_install
      when:
        - item.1.rc is defined
        - item.1.rc != 0

- name: Include configuration tasks for supervisor
  ansible.builtin.include_tasks:
    file: supervisord.yml
