---
- name: Check if Nix store exists
  ansible.builtin.stat:
    path: /nix/store
  register: nix_store_stat

- name: Check if Xvfb is already installed
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      nix-env -q | grep -q xorg-server
  changed_when: false
  failed_when: xvfb_check.rc not in [0, 1]
  register: xvfb_check
  when: nix_store_stat.stat.exists

- name: Ensure Xvfb package is installed on Nix image
  ansible.builtin.command: nix-env -iA nixpkgs.xorg.xvfb
  when:
    - nix_store_stat.stat.exists
    - xvfb_check.rc != 0
  register: xvfb_install
  changed_when: xvfb_install.rc == 0
