---
- name: Configure supervisor
  become: "{{ ansible_user_id != 'root' }}"
  when: xvfb_service_enabled
  block:

    - name: Ensures Xvfb profile is created
      ansible.builtin.template:
        dest: /etc/profile.d/10-xvfb.sh
        mode: "0644"
        src: profile-d-xvfb.j2

    - name: Check for supervisor configuration files
      ansible.builtin.stat:
        path: "{{ item }}"
      loop:
        - /etc/supervisord.conf
        - /etc/supervisor/supervisord.conf
      register: supervisor_conf_files

    - name: Ensure necessary directories exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - /etc/profile.d
        - /etc/supervisor/conf.d
#       - /var/log/supervisor
#       - /var/run

    - name: Create supervisor configuration file
      ansible.builtin.template:
        src: supervisord-xvfb.conf.j2
        dest: /etc/supervisor/supervisord.conf
        mode: "0644"
      notify: Reload supervisord
      when: supervisor_conf_files.results | map(attribute='stat.exists') | select | list | length == 0

    - name: Check for supervisor configuration files
      ansible.builtin.stat:
        path: "{{ item }}"
      loop:
        - /etc/supervisord.conf
        - /etc/supervisor/supervisord.conf
      register: supervisor_conf_files

    - name: Sets the current supervisor configuration file fact
      ansible.builtin.set_fact:
        supervisor_conf_file: >-
          {{ supervisor_conf_files.results | selectattr('stat.exists', 'true') | map(attribute='item') | first }}

    - name: Create Xvfb supervisor program configuration
      ansible.builtin.template:
        src: supervisord-xvfb-program.conf.j2
        dest: /etc/supervisor/conf.d/xvfb.conf
        mode: "0644"

    - name: Start supervisor daemon
      ansible.builtin.command: supervisord -c "{{ supervisor_conf_file }}"
      args:
        creates: /var/run/supervisord.pid
