---
- name: Configure supervisor
  become: "{{ ansible_user_id != 'root' }}"
  when: xvfb_service_enabled
  block:

    - name: Ensure necessary directories exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - /etc/profile.d
        - /etc/supervisor
        - /var/log/supervisor
        - /var/run

    - name: Ensures Xvfb profile is created
      ansible.builtin.template:
        dest: /etc/profile.d/10-xvfb.sh
        mode: "0644"
        src: profile-d-xvfb.j2

    - name: Check for supervisord configuration files
      ansible.builtin.stat:
        path: "{{ item }}"
      loop:
        - /etc/supervisord.conf
        - /etc/supervisor/supervisord.conf
      register: supervisor_conf_files

    - name: Sets the current supervisord configuration file fact
      ansible.builtin.set_fact:
        supervisor_conf_file: >-
          {{ supervisor_conf_files.results
            | selectattr('stat.exists')
            | map(attribute='item')
            | first
            | default('/etc/supervisor/supervisord.conf', true)
            | trim }}

    - name: Create supervisord configuration file
      ansible.builtin.template:
        src: supervisord-{{ xvfb_os_family }}.conf.j2
        dest: "{{ supervisor_conf_file }}"
        mode: "0644"
      notify:
        - All services are present
        - Restart Xvfb service
      when: supervisor_conf_files.results | map(attribute='stat.exists') | select | list | length == 0

    - name: Read supervisor configuration file content
      ansible.builtin.slurp:
        src: "{{ supervisor_conf_file }}"
      register: supervisor_conf_content

    - name: Read include.files, pidfile and socket from supervisor configuration file
      ansible.builtin.set_fact:
        supervisor_include_files: >-
          {{ (supervisor_conf_content.content | b64decode | community.general.from_ini).get('include', {})
            .get('files', '/etc/supervisor/conf.d').split(';')[0].split('#')[0] | trim }}
        supervisor_supervisord_pidfile: >-
          {{ (supervisor_conf_content.content | b64decode | community.general.from_ini).get('supervisord', {})
            .get('pidfile', '').split(';')[0].split('#')[0] | trim }}
        supervisor_unix_http_server_file: >-
          {{ (supervisor_conf_content.content | b64decode | community.general.from_ini).get('unix_http_server', {})
            .get('file', '').split(';')[0].split('#')[0] | trim }}

    - name: Read include's dir and extension from supervisor configuration file
      ansible.builtin.set_fact:
        supervisor_include_files_dir: >-
          {{ (supervisor_include_files.split('/')[:-1] | join('/'))
          if (supervisor_include_files is defined)
          else '/etc/supervisor/conf.d' | trim }}
        supervisor_include_files_ext: >-
          {{ supervisor_include_files.split('.')[-1]
          if (supervisor_include_files is defined and '.' in supervisor_include_files)
          else 'conf' | trim | replace('\n', '') }}
    - name: Ensure necessary supervisor directories exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - "{{ supervisor_include_files_dir }}"

    - name: Create Xvfb supervisor program configuration
      ansible.builtin.template:
        src: supervisord-xvfb-program.conf.j2
        dest: "{{ supervisor_include_files_dir }}/xvfb.{{ supervisor_include_files_ext | trim }}"
        mode: "0644"
      register: xvfb_supervisor_conf

    - name: Check if supervisord is running
      # noqa: command-instead-of-module - supervisorctl doesn't support checking for pid.
      ansible.builtin.command: >-
        supervisorctl
        {% if supervisor_conf_file is defined %}-c "{{ supervisor_conf_file }}"{% endif %}
        pid
      changed_when: false
      register: supervisord_status
      failed_when: false
      when: xvfb_service_manage | bool

    - name: Remove stale supervisor socket if not running
      ansible.builtin.file:
        path: "{{ supervisor_unix_http_server_file }}"
        state: absent
      when:
        - xvfb_service_manage | bool
        - supervisord_status.rc != 0
        - supervisor_unix_http_server_file is defined
        - supervisor_unix_http_server_file | length > 0

    - name: Remove stale supervisor pid if not running
      ansible.builtin.file:
        path: "{{ supervisor_supervisord_pidfile }}"
        state: absent
      when:
        - xvfb_service_manage | bool
        - supervisord_status.rc != 0
        - supervisor_supervisord_pidfile is defined
        - supervisor_supervisord_pidfile | length > 0

    - name: Start supervisord daemon
      ansible.builtin.command: supervisord -c "{{ supervisor_conf_file }}"
      when:
        - xvfb_service_manage | bool
        - supervisord_status.rc != 0
      changed_when: true

    - name: Wait for supervisor socket to be available
      ansible.builtin.wait_for:
        path: "{{ supervisor_unix_http_server_file | default('/var/run/supervisor.sock', true) }}"
        timeout: 30
      when:
        - xvfb_service_manage | bool
        - supervisord_status.rc != 0

    - name: Update supervisor to include new programs
      # noqa: no-handler command-instead-of-module - We need to update supervisor before continuing
      ansible.builtin.command: >-
        supervisorctl
        {% if supervisor_conf_file is defined %}-c "{{ supervisor_conf_file }}"{% endif %}
        update
      register: supervisor_update
      changed_when: >-
        "added process group" in supervisor_update.stdout or
        "updated process group" in supervisor_update.stdout
      when:
        - xvfb_service_enabled | bool
        - xvfb_service_manage | bool
