---
# Handlers file for xvfb role.

- name: Reload supervisord
  # Using killall in case supervisord is not running as a service.
  ansible.builtin.shell: |
    set -o pipefail
    kill -HUP $(cat /var/run/supervisord.pid) || supervisord -c /etc/supervisor/supervisord.conf
  changed_when: true
  when: xvfb_service_enabled | bool

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
  when: xvfb_service_enabled | bool
