---
# Handlers file for xvfb role.

- name: All services are present
  community.general.supervisorctl:
    name: all
    state: present
  changed_when: true
  when: xvfb_service_enabled | bool

- name: Restart Xvfb service
  community.general.supervisorctl:
    name: xvfb
    state: restarted
  changed_when: true
  when: xvfb_service_enabled | bool
