---
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: alpine-latest
    image: i386/alpine:latest
  - name: debian-latest
    image: debian:latest
  - name: nixos-latest
    image: nixos/nix:latest
  - name: ubuntu-jammy
    image: ubuntu:jammy
  - name: ubuntu-noble
    image: ubuntu:noble
  - name: ubuntu-latest
    image: ubuntu:latest
provisioner:
  config_options:
    defaults:
      remote_tmp: /tmp/.ansible-tmp-$${USER}
  name: ansible
  inventory:
    group_vars:
      all:
      #  ansible_user: nobody
verifier:
  name: ansible
