---
# Note: Keep keys and envs in alphabetical order.
name: Docker Publish

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  call-docker-build:
    name: Call Docker Build
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/docker-build.yml
    with:
      push: true
