---
name: Molecule

# yamllint disable-line rule:truthy
on:
  pull_request:
    paths-ignore:
      - '!.github/workflows/**'
      - '**.cfg'
      - '**.md'
      - '.*'
      - LICENSE
      - Pipfile*
  push:
    paths-ignore:
      - '!.github/workflows/**'
      - '**.cfg'
      - '**.md'
      - '.*'
      - LICENSE
      - Pipfile*

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - default
        platform:
          - alpine-latest
          - debian-latest
          - nixos-latest
          - ubuntu-jammy
          - ubuntu-noble
    env:
      MOLECULE_REPORT: molecule-${{ matrix.scenario }}-${{ matrix.platform }}-report.html
    steps:
      - uses: actions/checkout@v4
        with:
          path: ${{ github.repository }}
      - name: Install Ansible collections
        run: |
          pip install ansible-core
          ansible-galaxy collection install -r requirements.yml -p collections
        working-directory: ${{ github.repository }}
      - uses: gofrolist/molecule-action@v2
        env:
          ANSIBLE_FORCE_COLOR: '1'
          ANSIBLE_STDOUT_CALLBACK: ${{ runner.debug == '1' && 'debug' || 'ansible.builtin.default' }}
          ANSIBLE_CALLBACK_RESULT_FORMAT: yaml
        with:
          molecule_args: --scenario-name ${{ matrix.scenario }} --platform-name ${{ matrix.platform }}
          molecule_command: test
          molecule_options: ${{ runner.debug == '1' && '--verbose' || '' }}
          molecule_working_dir: ${{ github.repository }}
      - if: always()
        name: Ensure report file permissions are correct
        run: |
          sudo touch "${MOLECULE_REPORT}"
          sudo chmod 644 "${MOLECULE_REPORT}"
        working-directory: ${{ github.repository }}
      - if: always()
        name: Converts test report
        uses: patrick-werner/fhir-html-validation-to-markdown@1.0.0
        with:
          input_file: ${{ github.repository }}/${{ env.MOLECULE_REPORT }}
      # Debug with tmate on failure when debug logging is enabled.
      - if: ${{ failure() && runner.debug == '1' }}
        uses: mxschmitt/action-tmate@v3
    timeout-minutes: 40
